class CrawledUrl < ActiveRecord::Base
  attr_accessible :url, :title

  STATUS_COMPUTER_CLASSIFY_NONE    = 0
  STATUS_COMPUTER_CLASSIFY_SEO     = 1
  STATUS_COMPUTER_CLASSIFY_NOT_SEO = 2

  STATUS_HUMAN_CLASSIFY_NONE    = 0
  STATUS_HUMAN_CLASSIFY_SEO     = 1
  STATUS_HUMAN_CLASSIFY_NOT_SEO = 2
end
